version: 7.2.x-{build}

image:
- Visual Studio 2015

environment:
  BLD: debug
  matrix:
  - ARCH: x86
  - ARCH: x86
    BLD: release
  - ARCH: x64
  - ARCH: x64
    BLD: release

clone_depth: 50

install:
- cmd: '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%ARCH% /%BLD%'

build_script:
  - cmd: cd src && nmake -f Makefile.msft clean all && cd ..

test_script:
  - cmd: cd src && nmake -f Makefile.msft check
