version: 7.7.0-{build}

image:
- Visual Studio 2015

environment:
  BLD: debug
  TEST_TARGET: check
  matrix:
  - ARCH: x86
    CFLAGS_EXTRA: -DAO_ASSUME_VISTA /J
  - ARCH: x86
    BLD: release
  - ARCH: x64
    CFLAGS_EXTRA: -DAO_CMPXCHG16B_AVAILABLE
  - ARCH: x64
    BLD: release

clone_depth: 50

install:
- cmd: '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%ARCH% /%BLD%'

build_script:
- cmd: cd src && nmake -f Makefile.msft clean all CFLAGS_EXTRA="/WX %CFLAGS_EXTRA%" && cd ..

test_script:
- cmd: cd src && nmake -f Makefile.msft %TEST_TARGET% CFLAGS_EXTRA="/WX %CFLAGS_EXTRA%"
