version: 7.7.0-{build}

clone_depth: 50

environment:
  MS_SDK_VER: v7.1
  TEST_TARGET: check
  matrix:
  - CPU: x86
    BLD: debug
    CFLAGS_EXTRA: -DAO_ASSUME_VISTA -J
  - CPU: x86
    BLD: release
  - CPU: x64
    BLD: debug
    CFLAGS_EXTRA: -DAO_CMPXCHG16B_AVAILABLE
  - CPU: x64
    BLD: release

install:
  - cmd: '"C:\Program Files\Microsoft SDKs\Windows\%MS_SDK_VER%\Bin\SetEnv.cmd" /%CPU% /%BLD%'

build_script:
- cmd: cd src && nmake -f Makefile.msft clean all CFLAGS_EXTRA="/WX %CFLAGS_EXTRA%" && cd ..

test_script:
- cmd: cd src && nmake -f Makefile.msft %TEST_TARGET% CFLAGS_EXTRA="/WX %CFLAGS_EXTRA%"
