version: 7.7.0-{build}

image:
- Visual Studio 2019

environment:
  STUDIO_VERSION_EDITION: Studio\2019\Community
  PLATFORM_TYPE:
  TEST_TARGET: check
  matrix:
  - ARCH: x86
    CFLAGS_EXTRA: /J
  - ARCH: x86
    CFLAGS_EXTRA: -DNDEBUG
    WINSDK_VERSION: 8.1
  - ARCH: x64
    CFLAGS_EXTRA: -DAO_CMPXCHG16B_AVAILABLE
    WINSDK_VERSION: 8.1
  - ARCH: x86_x64
    CFLAGS_EXTRA: -DNDEBUG
  - ARCH: x86_arm
    TEST_TARGET: check-deps
  - ARCH: x64_arm64
    TEST_TARGET: check-deps

clone_depth: 50

install:
- cmd: '"C:\Program Files (x86)\Microsoft Visual %STUDIO_VERSION_EDITION%\VC\Auxiliary\Build\vcvarsall.bat" %ARCH% %PLATFORM_TYPE% %WINSDK_VERSION%'

build_script:
- cmd: cd src && nmake -f Makefile.msft clean all CFLAGS_EXTRA="/WX %CFLAGS_EXTRA%" && cd ..

test_script:
- cmd: cd src && nmake -f Makefile.msft %TEST_TARGET% CFLAGS_EXTRA="/WX %CFLAGS_EXTRA%"
