language: c

matrix:
  include:
  - os: linux
    compiler: clang
    env:
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: gcc
    env:
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: osx
  - os: linux
    env:
    - MAKEFILE_TARGET=distcheck
    - AO_REAL_VERSION=7.2i
  - os: linux
    env:
    - MAKEFILE_TARGET=dist
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    addons:
      apt:
        packages:
        - musl-tools
    compiler: musl-gcc

before_install:
- if [[ "$MAKEFILE_TARGET" == "dist"* ]]; then
    autoconf --version;
    automake --version;
    m4 --version;
    libtool --version || true;
  fi
- if [[ "$MAKEFILE_TARGET" == "" ]]; then MAKEFILE_TARGET=check; fi

install:
- if [[ "$WORKAROUND_ACLOCAL_MISSING" == true ]]; then
    autoreconf --force --install;
  fi

script:
- ./configure
- make -j $MAKEFILE_TARGET
- if [[ "$AO_REAL_VERSION" != "" ]]; then
    gzip --decompress libatomic_ops-*.tar.gz;
    mv libatomic_ops-*.tar libatomic_ops-$AO_REAL_VERSION.tar;
    gzip --best --verbose libatomic_ops-*.tar;
  fi

deploy:
  provider: releases
  api_key:
    secure: wDAkRwV0lFrzLqdMhrnzD+fVZDODB32q2riJKXKZ3eC70VdliJzX59G60iJqIdN6YSSGGjpDTcaKTmim/T1zgAW+UIcXvpveX3jtocmsJJemZyFKAT++hHbeakNr4Mhgs0ddv3+JsgX375KOmL+ZkUzW0+5uIf9CXK80kE5v6E6p5LC6+Jg8Tqj2uSmUDfrYCFdIDQ901vAjxdPbFsFL8STy0ahBhUCrTThi9emAMR2vBwxf+0We58la936hMFmXs320ZtYN4fksuxNMgQu/3HL/UZIINT2IXgstWiNoU3yK6Z5IvOKWw0iPLMg7SS6L4WYJTu4Z26YnIlJ8XM3f7hO+c+jdffup59O1oklCl6JwlbqNFWtZhfJ+TW8fX8rpsvZIovBI4oOsZthpMNcvb3ZZ6UczUbhaInCvcYl5aTw/8K63Vh2HhKTFdMYMLn1X+qNIfXyKRL15C8VZOHB3Os14G03FNPlTqFE4IRnU3TyXTKBIwYOXf5Nb7fmOYZ11lHejco3rE0n3MiqIL0QJAAwExozV6Af/aJefyTWqfycgaGEfUzBQQpcMVlrDJg1I+LU7vExYYYYYoVPCKHn3CDsmdftUpJcPeKMHuasrfp54RBnY+B9s+hJQRtA7C70JbtoJpC+nxfwIzprBkdLudD+mI52zgFmU7JC1UeWDBik=
  file: libatomic_ops-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    condition: $MAKEFILE_TARGET = distcheck
    repo: ivmai/libatomic_ops
    tags: true
