dist: xenial
language: c
os: linux

jobs:
  include:
  - compiler: clang
    env:
    - WORKAROUND_ACLOCAL_MISSING=true
  - compiler: gcc
    env:
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: osx
  - env:
    - MAKEFILE_TARGET=dist
    - WORKAROUND_ACLOCAL_MISSING=true
  - addons:
      apt:
        packages:
        - musl-tools
    compiler: musl-gcc
    env:
    - WORKAROUND_ACLOCAL_MISSING=true
  - env:
    - MAKEFILE_TARGET=distcheck
    - AO_REAL_VERSION=7.2l
    - AUTOMAKE_VER=1.14.1

before_install:
- if [[ "$AUTOMAKE_VER" != "" ]]; then
    GNUTOOLS_ROOT=`pwd`/../gnu-tools;
    export PATH=$GNUTOOLS_ROOT/bin:$PATH;
    GNU_DOWNLOAD_SITE=https://ftp.gnu.org/gnu;
    AUTOMAKE_XZ_URL=$GNU_DOWNLOAD_SITE/automake/automake-$AUTOMAKE_VER.tar.xz;
    wget --no-check-certificate -O - $AUTOMAKE_XZ_URL | tar xf - --xz --directory ~;
    (cd ~/automake-$AUTOMAKE_VER && ./configure --prefix=$GNUTOOLS_ROOT && make -j && make install);
  fi
- if [[ "$MAKEFILE_TARGET" == "dist"* ]]; then
    autoconf --version;
    automake --version;
    m4 --version;
    libtool --version || true;
  fi
- if [[ "$MAKEFILE_TARGET" == "" ]]; then MAKEFILE_TARGET=check; fi

install:
- if [[ "$WORKAROUND_ACLOCAL_MISSING" == true ]]; then
    autoreconf --force --install;
  fi

script:
- ./configure
- make -j $MAKEFILE_TARGET
- if [[ "$AO_REAL_VERSION" != "" ]]; then
    gzip --decompress libatomic_ops-*.tar.gz;
    mv libatomic_ops-*.tar libatomic_ops-$AO_REAL_VERSION.tar;
    gzip --best --verbose libatomic_ops-*.tar;
  fi

deploy:
  provider: releases
  edge: true
  file: libatomic_ops-*.tar.gz
  file_glob: true
  on:
    condition: $MAKEFILE_TARGET = distcheck
    repo: ivmai/libatomic_ops
    tags: true
